# Generated by Django 5.1.2 on 2024-11-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0006_delete_item_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_userid', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_address', models.CharField(blank=True, max_length=255)),
                ('user_phoneNum', models.CharField(blank=True, max_length=11)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='imageprod/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.users')),
            ],
        ),
    ]
